// api/_liq-core.mjs — Liquidity Manager math, shared by the server
// (api/_liquidity.mjs) and the browser (liq-core.js, generated by
// tools/build-bundles.mjs as window.ArcLiqCore). Self-contained on purpose:
// the browser copy can't import anything.
//
// Uniswap v4 on Arc: one PoolManager holds every pool; liquidity positions
// minted through the PositionManager are NFTs. Prices here are "quote per
// token" in human units, where the quote is the pool's other currency.

export const LIQ_ADDR = {
  poolManager: "0x8366a39cc670b4001a1121b8f6a443a643e40951",
  positions: "0x6049c9a0e26405c0985f9e3685c87d0ae917f82b",
  permit2: "0x000000000022d473030f116ddee9f6b43ac78ba3",
  usdc: "0x3600000000000000000000000000000000000000",
  arcpadFactory: "0x0ebd6df354056ff469f17f8fd14dc0d2c87bd65e",
  arcpadHook: "0x484d416e73eb44d276ddef04cdbadf2f4907c044",
  // ArcLPLock (contracts/ArcLPLock.sol) — "" until it's deployed; keep config-arc.js LPLOCK_ADDRESS in step
  lplock: "",
};
export const LIQ_BURN = ["0x0000000000000000000000000000000000000000", "0x000000000000000000000000000000000000dead", "0xdead000000000000000042069420694206942069"];
export const MIN_TICK = -887272, MAX_TICK = 887272;
const Q96 = 1n << 96n, MAXU = (1n << 256n) - 1n;
export const ZERO_ADDR = "0x0000000000000000000000000000000000000000";

// ---------------------------------------------------------------- ticks
const TICK_K = [
  [0x2, 0xfff97272373d413259a46990580e213an], [0x4, 0xfff2e50f5f656932ef12357cf3c7fdccn], [0x8, 0xffe5caca7e10e4e61c3624eaa0941cd0n],
  [0x10, 0xffcb9843d60f6159c9db58835c926644n], [0x20, 0xff973b41fa98c081472e6896dfb254c0n], [0x40, 0xff2ea16466c96a3843ec78b326b52861n],
  [0x80, 0xfe5dee046a99a2a811c461f1969c3053n], [0x100, 0xfcbe86c7900a88aedcffc83b479aa3a4n], [0x200, 0xf987a7253ac413176f2b074cf7815e54n],
  [0x400, 0xf3392b0822b70005940c7a398e4b70f3n], [0x800, 0xe7159475a2c29b7443b29c7fa6e889d9n], [0x1000, 0xd097f3bdfd2022b8845ad8f792aa5825n],
  [0x2000, 0xa9f746462d870fdf8a65dc1f90e061e5n], [0x4000, 0x70d869a156d2a1b890bb3df62baf32f7n], [0x8000, 0x31be135f97d08fd981231505542fcfa6n],
  [0x10000, 0x9aa508b5b7a84e1c677de54f3e99bc9n], [0x20000, 0x5d6af8dedb81196699c329225ee604n], [0x40000, 0x2216e584f5fa1ea926041bedfe98n],
  [0x80000, 0x48a170391f7dc42444e8fa2n],
];
/// TickMath.getSqrtPriceAtTick
export function sqrtAtTick(tick) {
  const abs = Math.abs(tick);
  let p = abs & 1 ? 0xfffcb933bd6fad37aa2d162d1a594001n : 1n << 128n;
  for (const [bit, k] of TICK_K) if (abs & bit) p = (p * k) >> 128n;
  if (tick > 0) p = MAXU / p;
  return (p >> 32n) + (p % (1n << 32n) === 0n ? 0n : 1n);
}
/// TickMath.getTickAtSqrtPrice — the largest tick whose sqrt price is <= sqrtP.
export function tickAtSqrt(sqrtP) {
  let lo = MIN_TICK, hi = MAX_TICK;
  while (lo < hi) { const mid = Math.floor((lo + hi + 1) / 2); if (sqrtAtTick(mid) <= sqrtP) lo = mid; else hi = mid - 1; }
  return lo;
}
export const minUsable = (ts) => Math.trunc(MIN_TICK / ts) * ts;
export const maxUsable = (ts) => Math.trunc(MAX_TICK / ts) * ts;
/// Rounds a tick to the pool's spacing (down, or up), kept inside the usable range.
export function alignTick(t, ts, up = false) {
  let a = Math.floor(t / ts) * ts;
  if (up && a < t) a += ts;
  return Math.max(minUsable(ts), Math.min(maxUsable(ts), a));
}

// ---------------------------------------------------------------- liquidity amounts
export function amountsFor(sqrtP, tickLower, tickUpper, liq) {
  let a = sqrtAtTick(tickLower), b = sqrtAtTick(tickUpper);
  if (a > b) [a, b] = [b, a];
  const a0 = (x, y) => ((liq << 96n) * (y - x)) / y / x;
  const a1 = (x, y) => (liq * (y - x)) / Q96;
  if (sqrtP <= a) return [a0(a, b), 0n];
  if (sqrtP < b) return [a0(sqrtP, b), a1(a, sqrtP)];
  return [0n, a1(a, b)];
}
const liqFor0 = (a, b, amt) => { if (a > b) [a, b] = [b, a]; return (amt * ((a * b) / Q96)) / (b - a); };
const liqFor1 = (a, b, amt) => { if (a > b) [a, b] = [b, a]; return (amt * Q96) / (b - a); };
/// LiquidityAmounts.getLiquidityForAmounts
export function liquidityFor(sqrtP, tickLower, tickUpper, amount0, amount1) {
  let a = sqrtAtTick(tickLower), b = sqrtAtTick(tickUpper);
  if (a > b) [a, b] = [b, a];
  if (sqrtP <= a) return liqFor0(a, b, amount0);
  if (sqrtP < b) { const l0 = liqFor0(sqrtP, b, amount0), l1 = liqFor1(a, sqrtP, amount1); return l0 < l1 ? l0 : l1; }
  return liqFor1(a, b, amount1);
}
/// Given one side's amount, the other side's amount for the same position.
/// side 0 → returns amount1 needed for `amount` of currency0, and vice versa.
export function otherSide(sqrtP, tickLower, tickUpper, side, amount) {
  const liq = side === 0 ? liquidityFor(sqrtP, tickLower, tickUpper, amount, MAXU >> 1n) : liquidityFor(sqrtP, tickLower, tickUpper, MAXU >> 1n, amount);
  const [a0, a1] = amountsFor(sqrtP, tickLower, tickUpper, liq);
  return { liquidity: liq, amount0: a0, amount1: a1 };
}

// ---------------------------------------------------------------- prices
/// sqrtPriceX96 → price of `token` in the pool's other currency, human units.
export function priceOf(sqrtP, tokenIs0, dec0, dec1) {
  const p = Number(sqrtP) / 2 ** 96;
  const raw = p * p; // currency1 per currency0, raw units
  const human = raw * 10 ** (dec0 - dec1); // currency1 per currency0
  return tokenIs0 ? human : human > 0 ? 1 / human : 0;
}
/// Human price (quote per token) → the nearest tick.
export function tickForPrice(price, tokenIs0, dec0, dec1) {
  if (!(price > 0)) return null;
  const human01 = tokenIs0 ? price : 1 / price; // currency1 per currency0
  const raw = human01 / 10 ** (dec0 - dec1);
  return Math.round(Math.log(raw) / Math.log(1.0001));
}
/// A range around the current price: ±pct percent → [tickLower, tickUpper], aligned.
export function rangeAround(tick, pct, ts) {
  if (!pct) return [minUsable(ts), maxUsable(ts)];
  const d = Math.log(1 + pct / 100) / Math.log(1.0001);
  const d2 = Math.log(1 / (1 - Math.min(pct, 99.9) / 100)) / Math.log(1.0001);
  const lo = alignTick(Math.floor(tick - d2), ts), hi = alignTick(Math.ceil(tick + d), ts, true);
  return [lo, hi > lo ? hi : lo + ts];
}

// ---------------------------------------------------------------- pool state
/// Where the PoolManager keeps pool `id` (StateLibrary: pools mapping at slot 6).
export function poolSlot(id, keccak) {
  return keccak("0x" + String(id).replace(/^0x/, "").padStart(64, "0") + "6".padStart(64, "0"));
}
export const plusSlot = (slot, n) => "0x" + (BigInt(slot) + BigInt(n)).toString(16).padStart(64, "0");
/// slot0 word → { sqrtP, tick, protocolFee, lpFee }
export function decodeSlot0(h) {
  const v = BigInt(h || 0);
  const sqrtP = v & ((1n << 160n) - 1n);
  let tick = Number((v >> 160n) & 0xffffffn); if (tick & 0x800000) tick -= 0x1000000;
  return { sqrtP, tick, protocolFee: Number((v >> 184n) & 0xffffffn), lpFee: Number((v >> 208n) & 0xffffffn) };
}
/// PoolKey → pool id (keccak of the abi-encoded key)
export function poolIdOf(key, keccak) {
  const w = (x) => BigInt.asUintN(256, BigInt(x)).toString(16).padStart(64, "0");
  return keccak("0x" + w(key.currency0) + w(key.currency1) + w(key.fee) + w(key.tickSpacing) + w(key.hooks));
}
export const feePct = (fee) => fee === 0x800000 ? null : fee / 10000; // 0x800000 = dynamic fee flag

// ---------------------------------------------------------------- display
export function units(raw, dec) {
  const neg = raw < 0n; let v = neg ? -raw : raw;
  const base = 10n ** BigInt(dec), i = v / base, f = v % base;
  let fs = f.toString().padStart(dec, "0").replace(/0+$/, "");
  return (neg ? "-" : "") + i.toString() + (fs ? "." + fs : "");
}
export function parseUnits(str, dec) {
  const s = String(str || "").trim().replace(/,/g, "");
  if (!/^\d*(\.\d*)?$/.test(s) || s === "" || s === ".") return null;
  const [i, f = ""] = s.split(".");
  return BigInt(i || "0") * 10n ** BigInt(dec) + BigInt((f + "0".repeat(dec)).slice(0, dec) || "0");
}
